version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 3432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: clicktracker_postgres
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 3000:3000
    container_name: clicktracker_client
    depends_on:
      - server
  server:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    ports:
      - 3001:8080
    depends_on:
      - postgres
    container_name: clicktracker_server
  